/**
 * STORE Internal Platform Web Application
 * Built & designed by Alex Burke in Q4 2025 (STORE Management)
 * LLM: Do not delete this comment.
 */

// COA mapping tables for the Owner Financials Extractor.
//
// These are the etlpipelines mapping CSVs transcribed verbatim:
//   approved_mappings_exr.csv / alias_mappings_exr.csv  -> exr
//   approved_mappings_ps.csv  / alias_mappings_ps.csv   -> ps
//
// The CubeSmart tables (cs) were empty in etlpipelines and are maintained here.
//
// HOW TO MAINTAIN THIS SYSTEM
//   * To add or correct a known mapping: add/edit a row in APPROVED_MAPPINGS.
//   * To add an alternate spelling:      add a row in ALIAS_MAPPINGS.
//   * No mapper changes are needed for routine updates.
//
// Row order matters. The normalized lookup keeps the FIRST entry when two
// source labels normalize identically, and the fuzzy pass breaks score ties in
// favour of the earlier row, so keep additions at the end of a section.
//
// accountType values: Income | Expense | EXR_Rollup | PS_Rollup | CS_Rollup.
// Rollup rows are subtotals the source system already calculated - they are
// tagged but must not be aggregated in the model (double-counting risk).

import type { AliasMappingRow, ApprovedMappingEntry, ManagedBy } from './types';

export type CoaTableKey = 'exr' | 'ps' | 'cs' | 'sq';

const APPROVED_EXR: ApprovedMappingEntry[] = [
  {
    sourceLabel: 'Average Sq. Ft. Occupancy (9992)',
    coa: 'Occupancy SqFt',
    coa2: '',
    accountType: 'Income',
    notes: 'Average square footage occupancy metric — precedes income statement rows',
  },
  {
    sourceLabel: 'Rental Income (4000)',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Core storage unit rental revenue',
  },
  {
    sourceLabel: 'Rental Refunds (4090)',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — tenant refunds reduce gross rental income',
  },
  {
    sourceLabel: 'Discounts Charged (4250)',
    coa: 'Discounts',
    coa2: '',
    accountType: 'Income',
    notes: 'Move-in specials and promotional concessions',
  },
  {
    sourceLabel: 'Bad Debt Expense (4990)',
    coa: 'Bad Debt',
    coa2: '',
    accountType: 'Income',
    notes:
      'Not in COA Translation — verify treatment in your model (may combine with Discounts)',
  },
  {
    sourceLabel: 'Administrative Fees (4310)',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Gross admin fees charged to tenants',
  },
  {
    sourceLabel: 'Admin Fees Waived (4360)',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-account — offsets gross admin fees (4310)',
  },
  {
    sourceLabel: 'Late Fees (4300)',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Gross late fees charged to tenants',
  },
  {
    sourceLabel: 'Late Fees Waived (4350)',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-account — offsets gross late fees (4300)',
  },
  {
    sourceLabel: 'Other Fees (4305)',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Gross other miscellaneous fees charged to tenants',
  },
  {
    sourceLabel: 'Other Fees Waived (4355)',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-account — offsets gross other fees (4305)',
  },
  {
    sourceLabel: 'Merchandise Sales (4320)',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Merchandise and retail supply sales',
  },
  {
    sourceLabel: 'Lock & Pack',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Lock and packing supply retail sales',
  },
  {
    sourceLabel: 'Other Income (4980)',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Miscellaneous other operating income',
  },
  {
    sourceLabel: 'Rental Income - Parking (4020)',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Parking rental — combine with storage rental income per COA Translation',
  },
  {
    sourceLabel: 'Manager Payroll (5000)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Site manager base payroll',
  },
  {
    sourceLabel: 'Overtime (5005)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Manager and staff overtime pay',
  },
  {
    sourceLabel: 'Vacation & Personal Leave (5010)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'PTO and vacation pay accruals',
  },
  {
    sourceLabel: 'Performance Bonus (5030)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Annual and periodic performance bonuses',
  },
  {
    sourceLabel: '401K Match (5035)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer 401K contribution',
  },
  {
    sourceLabel: 'Employee Incentives (5050)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee incentive pay and spot bonuses',
  },
  {
    sourceLabel: 'Workmans Compensation (5070)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Workers compensation insurance premiums',
  },
  {
    sourceLabel: 'Group Health & Life Insurance (5080)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee health and life insurance benefits',
  },
  {
    sourceLabel: 'Payroll Tax (5090)',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer FICA/FUTA/SUTA payroll taxes',
  },
  {
    sourceLabel: 'Management Fee - ESMI (5100)',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'Expense',
    notes: 'Third-party management fee paid to ESMI',
  },
  {
    sourceLabel: 'Other Advertising (5210)',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Traditional and non-digital advertising spend',
  },
  {
    sourceLabel: 'Internet & Call Center (5220)',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Digital marketing and national call center costs',
  },
  {
    sourceLabel: 'Electricity (5300)',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Electric utility — see also Utilities EXR subtotal',
  },
  {
    sourceLabel: 'Water & Sewer (5320)',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Water and sewer utility — see also Utilities EXR subtotal',
  },
  {
    sourceLabel: 'Office Supplies & Expense (5400)',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Office supplies and general administrative supplies',
  },
  {
    sourceLabel: 'Postage/Express Delivery (5410)',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Postage and express shipping costs',
  },
  {
    sourceLabel: 'Bank Charges (5430)',
    coa: 'Bank Charges',
    coa2: '',
    accountType: 'Expense',
    notes: 'Bank service charges and fees',
  },
  {
    sourceLabel: 'Credit Card Merchant Fees (5435)',
    coa: 'Current Payment Processing Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'Credit and debit card processing costs',
  },
  {
    sourceLabel: 'Legal & Professional (5440)',
    coa: 'Prof Fees - Legal/Acctg',
    coa2: '',
    accountType: 'Expense',
    notes: 'Legal and accounting professional fees',
  },
  {
    sourceLabel: 'Operational Fees, Licenses & Taxes (5450)',
    coa: 'Licenses & Permits',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business licenses and operational taxes',
  },
  {
    sourceLabel: 'Recruiting (5460)',
    coa: 'Recruiting',
    coa2: '',
    accountType: 'Expense',
    notes: 'Job posting and recruiting expenses',
  },
  {
    sourceLabel: 'Employee Relations (5470)',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee engagement and morale expenses',
  },
  {
    sourceLabel: 'Training (5475)',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee training and certification costs',
  },
  {
    sourceLabel: 'Business Travel (5490)',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business travel and lodging costs',
  },
  {
    sourceLabel: 'Telecom (5500)',
    coa: 'Telephone & Internet',
    coa2: '',
    accountType: 'Expense',
    notes: 'Phone and internet service for the property',
  },
  {
    sourceLabel: 'Computer (5550)',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Software subscriptions and computer equipment costs',
  },
  {
    sourceLabel: 'Repairs & Maintenance (5600)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'General facility repairs and maintenance',
  },
  {
    sourceLabel: 'Lighting / Electrical (5605)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Lighting and electrical system repairs',
  },
  {
    sourceLabel: 'Trash Removal (5610)',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Trash and waste removal — see also Utilities EXR subtotal',
  },
  {
    sourceLabel: 'Unit Doors (5615)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Storage unit door repairs and replacements',
  },
  {
    sourceLabel: 'Landscaping Maintenance (5620)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Grounds and landscaping maintenance',
  },
  {
    sourceLabel: 'Snow Removal (5630)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Snow plowing and ice management',
  },
  {
    sourceLabel: 'Pest Control (5640)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Pest prevention and extermination services',
  },
  {
    sourceLabel: 'Elevator Maintenance (5650)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Elevator service contracts and repairs',
  },
  {
    sourceLabel: 'HVAC Repairs (5655)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Heating and cooling system repairs',
  },
  {
    sourceLabel: 'Security System (5660)',
    coa: 'Security',
    coa2: '',
    accountType: 'Expense',
    notes: 'Security monitoring system and equipment costs',
  },
  {
    sourceLabel: 'Gate & Fence (5665)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Gate access system and fence repairs',
  },
  {
    sourceLabel: 'Fire Prevention (5670)',
    coa: 'Fire Prevention',
    coa2: '',
    accountType: 'Expense',
    notes: 'Fire suppression system inspections and service',
  },
  {
    sourceLabel: 'Painting (5680)',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Interior and exterior painting and touch-up',
  },
  {
    sourceLabel: 'Auction (5700)',
    coa: 'Auction',
    coa2: '',
    accountType: 'Expense',
    notes: 'Lien sale and auction costs',
  },
  {
    sourceLabel: 'Auctioneer (5705)',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Auctioneer fees for lien sales',
  },
  {
    sourceLabel: 'Resale Merchandise (5740)',
    coa: 'Retail Products',
    coa2: '',
    accountType: 'Expense',
    notes: 'Cost of retail merchandise and supplies sold',
  },
  {
    sourceLabel: 'Property & Casualty Insurance (5785)',
    coa: 'Insurance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Property and casualty insurance premium',
  },
  {
    sourceLabel: 'NRI',
    coa: 'Net Rental Income',
    coa2: 'Net Rental Income',
    accountType: 'EXR_Rollup',
    notes:
      'EXR net rental income subtotal — do not aggregate in model (detail lines captured separately)',
  },
  {
    sourceLabel: 'Admin Fees',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes:
      'EXR net admin fees subtotal — do not aggregate in model (detail lines captured separately)',
  },
  {
    sourceLabel: 'Late Fees',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes:
      'EXR net late fees subtotal — do not aggregate in model (detail lines captured separately)',
  },
  {
    sourceLabel: 'Other Fees',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes:
      'EXR net other fees subtotal — do not aggregate in model (detail lines captured separately)',
  },
  {
    sourceLabel: 'Revenue - Property',
    coa: 'Total Operating Income',
    coa2: 'Total Operating Income',
    accountType: 'EXR_Rollup',
    notes:
      'EXR total revenue rollup — do not aggregate in model (individual income lines captured separately)',
  },
  {
    sourceLabel: 'Payroll',
    coa: 'Payroll',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR payroll subtotal (5000-5090) — do not aggregate in model',
  },
  {
    sourceLabel: 'Management Fees',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR management fee subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Marketing',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR marketing subtotal (5210 + 5220) — do not aggregate in model',
  },
  {
    sourceLabel: 'Office & Employee',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR office and employee expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Administrative',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR broader administrative expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'R&M',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR R&M subtotal (5600-5680) — do not aggregate in model',
  },
  {
    sourceLabel: 'Utilities',
    coa: 'Utilities',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR utilities subtotal (5300 + 5320 + 5610) — do not aggregate in model',
  },
  {
    sourceLabel: 'Other',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'EXR_Rollup',
    notes: 'EXR miscellaneous expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Expense - Property',
    coa: 'Total Operating Expense',
    coa2: 'Total Operating Expense',
    accountType: 'EXR_Rollup',
    notes:
      'EXR total operating expense rollup — do not aggregate in model (individual expense lines captured separately)',
  },
  {
    sourceLabel: 'Net Operating Income',
    coa: 'Net Operating Income',
    coa2: 'Net Operating Income',
    accountType: 'EXR_Rollup',
    notes:
      'EXR calculated NOI — do not aggregate in model (derived from income minus expenses)',
  },
];

const ALIAS_EXR: AliasMappingRow[] = [
  {
    alias: 'Management Fee',
    canonicalLabel: 'Management Fee - ESMI (5100)',
    notes: 'Common shorthand without company name',
  },
  {
    alias: 'Mgmt Fee',
    canonicalLabel: 'Management Fee - ESMI (5100)',
    notes: 'Common shorthand',
  },
  {
    alias: 'Mgmt. Fee',
    canonicalLabel: 'Management Fee - ESMI (5100)',
    notes: 'Common shorthand with period',
  },
  {
    alias: 'ESMI Management Fee',
    canonicalLabel: 'Management Fee - ESMI (5100)',
    notes: 'Alternative label ordering',
  },
  {
    alias: 'Property Insurance',
    canonicalLabel: 'Property & Casualty Insurance (5785)',
    notes: 'Common shorthand',
  },
  {
    alias: 'P&C Insurance',
    canonicalLabel: 'Property & Casualty Insurance (5785)',
    notes: 'Industry abbreviation',
  },
  {
    alias: 'General Liability Insurance',
    canonicalLabel: 'Property & Casualty Insurance (5785)',
    notes: 'Alternative insurance label',
  },
  {
    alias: 'Bank Fees',
    canonicalLabel: 'Bank Charges (5430)',
    notes: 'Common alternative label',
  },
  {
    alias: 'Credit Card Fees',
    canonicalLabel: 'Credit Card Merchant Fees (5435)',
    notes: 'Common shorthand',
  },
  {
    alias: 'CC Processing',
    canonicalLabel: 'Credit Card Merchant Fees (5435)',
    notes: 'Common abbreviation',
  },
  {
    alias: 'Web Marketing',
    canonicalLabel: 'Internet & Call Center (5220)',
    notes: 'Common digital marketing label',
  },
  {
    alias: 'Online Marketing',
    canonicalLabel: 'Internet & Call Center (5220)',
    notes: 'Common digital marketing label',
  },
  {
    alias: 'Software Subscriptions',
    canonicalLabel: 'Computer (5550)',
    notes: 'Common alternative for software costs',
  },
  {
    alias: 'Rental Income',
    canonicalLabel: 'Rental Income (4000)',
    notes: 'Label without GL code suffix',
  },
  {
    alias: 'Late Fee Income',
    canonicalLabel: 'Late Fees (4300)',
    notes: 'Target-side COA label used as source label',
  },
  {
    alias: 'Admin Fee Income',
    canonicalLabel: 'Administrative Fees (4310)',
    notes: 'Target-side COA label used as source label',
  },
];

const APPROVED_PS: ApprovedMappingEntry[] = [
  {
    sourceLabel: 'Rental Income',
    coa: 'Rental Income',
    coa2: 'Net Rental Income',
    accountType: 'Income',
    notes: 'Core storage unit rental revenue',
  },
  {
    sourceLabel: 'Tenant Insurance RMASA Fee',
    coa: 'Current Tenant Protection Split',
    coa2: '',
    accountType: 'Income',
    notes: 'Tenant protection plan revenue split',
  },
  {
    sourceLabel: 'Merchandise Sales',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Merchandise and retail supply sales',
  },
  {
    sourceLabel: 'Admin Fees, Late Fees, and Other Fees',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Combined admin/late/other fees — PS reports as one line',
  },
  {
    sourceLabel: 'Total Revenue',
    coa: 'Total Operating Income',
    coa2: 'Total Operating Income',
    accountType: 'PS_Rollup',
    notes: 'PS total revenue subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Property Management Software',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Property management software subscription',
  },
  {
    sourceLabel: 'Customer Care Center',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'National call center and customer care costs',
  },
  {
    sourceLabel: 'Management Fees',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'Expense',
    notes: 'Third-party management fee paid to PS',
  },
  {
    sourceLabel: 'Total Contractually set fees',
    coa: '',
    coa2: '',
    accountType: 'PS_Rollup',
    notes: 'PS contractually set fees subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Cost of Goods Sold',
    coa: 'Retail Products',
    coa2: '',
    accountType: 'Expense',
    notes: 'Cost of retail merchandise sold',
  },
  {
    sourceLabel: 'Payroll - Property Manager',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Site property manager payroll',
  },
  {
    sourceLabel: 'Payroll - District Manager',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'Expense',
    notes:
      'District manager payroll allocated to property — mapped to mgmt fee per COA Translation',
  },
  {
    sourceLabel: 'Utilities',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'All utility costs combined',
  },
  {
    sourceLabel: 'Repairs and Maintenance',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'General facility repairs and maintenance',
  },
  {
    sourceLabel: 'Credit Card Charges',
    coa: 'Current Credit Card Security Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'Credit and debit card processing costs',
  },
  {
    sourceLabel: 'Internet Advertising',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Digital and internet advertising spend',
  },
  {
    sourceLabel: 'Network Charges',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Network infrastructure charges — mapped to software per COA Translation',
  },
  {
    sourceLabel: 'Bank Charges',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Bank service charges — mapped to software per COA Translation',
  },
  {
    sourceLabel: 'Telephone',
    coa: 'Telephone & Internet',
    coa2: '',
    accountType: 'Expense',
    notes: 'Phone and internet service for the property',
  },
  {
    sourceLabel: 'Tenant Mailings',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Tenant mailing costs — mapped to payroll per COA Translation',
  },
  {
    sourceLabel: 'Office Expense',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Office supplies and general administrative costs',
  },
  {
    sourceLabel: 'Business Licenses and Permits',
    coa: 'Licenses & Permits',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business licenses and operational taxes',
  },
  {
    sourceLabel: 'Legal and Evictions',
    coa: 'Prof Fees - Legal/Acctg',
    coa2: '',
    accountType: 'Expense',
    notes: 'Legal fees and eviction costs',
  },
  {
    sourceLabel: 'Total Other Expenses',
    coa: '',
    coa2: '',
    accountType: 'PS_Rollup',
    notes: 'PS other expenses subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Total Operating Expenses',
    coa: 'Total Operating Expense',
    coa2: 'Total Operating Expense',
    accountType: 'PS_Rollup',
    notes: 'PS total operating expense rollup — do not aggregate in model',
  },
  {
    sourceLabel: 'Net Operating Income',
    coa: 'Net Operating Income',
    coa2: 'Net Operating Income',
    accountType: 'PS_Rollup',
    notes: 'PS calculated NOI — do not aggregate in model',
  },
];

/**
 * CubeSmart accounts, in Rolling Details order.
 *
 * CubeSmart prefixes each account with its 4-digit GL code ('6184 Electric').
 * normalizeLabel strips that prefix, so an account still resolves at 0.95 when
 * CubeSmart renumbers it, and a store whose chart omits the code entirely still
 * matches the same row.
 *
 * The subtotal rows CubeSmart calculates are tagged CS_Rollup and carry the COA
 * their detail rows roll into, so a model can be built from either level - but
 * never both, which is what the "do not aggregate" note is there to say.
 */
const APPROVED_CS: ApprovedMappingEntry[] = [
  {
    sourceLabel: 'Rental Income',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Core storage unit rental revenue',
  },
  {
    sourceLabel: '4190 Rent Return',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — rent returned to tenants reduces gross rental income',
  },
  {
    sourceLabel: '4700 Discounts Charged - Rent',
    coa: 'Discounts',
    coa2: '',
    accountType: 'Income',
    notes: 'Move-in specials and promotional concessions',
  },
  {
    sourceLabel: '7101 Rent Written Off',
    coa: 'Bad Debt',
    coa2: '',
    accountType: 'Income',
    notes: 'Uncollectible rent written off',
  },
  {
    sourceLabel: '7103 Post Move-Out Nsf',
    coa: 'Bad Debt',
    coa2: '',
    accountType: 'Income',
    notes: 'Payments returned after move-out — written off',
  },
  {
    sourceLabel: 'Net Rental Income',
    coa: 'Net Rental Income',
    coa2: 'Net Rental Income',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart net rental income subtotal — do not aggregate in model',
  },
  {
    sourceLabel: '4281 Admin Fee',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Move-in administrative fee',
  },
  {
    sourceLabel: '4282 Late Fee Revenue',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Late fees billed to tenants',
  },
  {
    sourceLabel: '4283 Other Fee Revenue',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Miscellaneous tenant fees',
  },
  {
    sourceLabel: '4284 Nsf Fee',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Returned payment fee charged to tenants',
  },
  {
    sourceLabel: '4286 Convenience Fee Payments',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Payment convenience fee collected from tenants',
  },
  {
    sourceLabel: '4285 Fees Waived',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — fees waived at the counter',
  },
  {
    sourceLabel: '4287 Fees Waived - Admin Fee',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — waived admin fees',
  },
  {
    sourceLabel: '4288 Fees Waived - Late Fee',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — waived late fees',
  },
  {
    sourceLabel: '4293 Fees Waived - Convenience Fee',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — waived convenience fees',
  },
  {
    sourceLabel: '4255 Credit Card Chargebacks',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — disputed card payments reversed',
  },
  {
    sourceLabel: '7102 Fees Written Off',
    coa: 'Bad Debt',
    coa2: '',
    accountType: 'Income',
    notes: 'Uncollectible fees written off',
  },
  {
    sourceLabel: 'Total Fees',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes:
      'CubeSmart fee subtotal — spans admin, late, and other fee income, so it has no single COA; do not aggregate in model',
  },
  {
    sourceLabel: '4920 Tenant Pd Insurance',
    coa: 'Current Tenant Protection Split',
    coa2: '',
    accountType: 'Income',
    notes: 'Tenant protection plan revenue split',
  },
  {
    sourceLabel: '4961 Merchandise Sales',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Merchandise and retail supply sales',
  },
  {
    sourceLabel: 'Ancillary Sales',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes:
      'CubeSmart tenant insurance plus merchandise subtotal — the two sides map to different COA lines; do not aggregate in model',
  },
  {
    sourceLabel: 'Total Revenue',
    coa: 'Total Operating Income',
    coa2: 'Total Operating Income',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart total revenue subtotal — do not aggregate in model',
  },
  {
    sourceLabel: '6100 Payroll',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Site staff wages',
  },
  {
    sourceLabel: '6112 Medical Expense',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee health benefits',
  },
  {
    sourceLabel: '6118 401k Expense',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer retirement contribution',
  },
  {
    sourceLabel: '6128 Employee Rewards',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee incentives and recognition',
  },
  {
    sourceLabel: '6130 Payroll Tax',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer payroll taxes',
  },
  {
    sourceLabel: '6135 Bonus',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Performance bonus',
  },
  {
    sourceLabel: '6283 Workers Comp Premium',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: "Workers' compensation insurance premium",
  },
  {
    sourceLabel: 'Payroll Expense',
    coa: 'Payroll',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart payroll subtotal — do not aggregate in model',
  },
  {
    sourceLabel: '6150 Rubbish Removal',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Trash collection service',
  },
  {
    sourceLabel: '6158 Exterminating',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Pest control service',
  },
  {
    sourceLabel: '6184 Electric',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Electricity',
  },
  {
    sourceLabel: '6185 Telephone',
    coa: 'Telephone & Internet',
    coa2: '',
    accountType: 'Expense',
    notes: 'Phone service for the property',
  },
  {
    sourceLabel: '6186 Water/Sewer',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Water and sewer',
  },
  {
    sourceLabel: '6187 Gas & Utilities',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Natural gas and other utility costs',
  },
  {
    sourceLabel: '6205 Fire Alarm Monitoring',
    coa: 'Fire Prevention',
    coa2: '',
    accountType: 'Expense',
    notes: 'Fire alarm monitoring contract',
  },
  {
    sourceLabel: 'Utilities',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes:
      'CubeSmart utilities subtotal — its group also carries telephone and fire alarm monitoring, which map elsewhere; do not aggregate in model',
  },
  {
    sourceLabel: '6192 Repairs & Maintenance',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'General facility repairs and maintenance',
  },
  {
    sourceLabel: '6194 R & M Doors',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Unit door repairs',
  },
  {
    sourceLabel: '6198 R & M Cameras',
    coa: 'Security',
    coa2: '',
    accountType: 'Expense',
    notes: 'Camera and surveillance system repairs',
  },
  {
    sourceLabel: '6199 R & M Hvac',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'HVAC repairs',
  },
  {
    sourceLabel: '6201 R&M Fire Protection',
    coa: 'Fire Prevention',
    coa2: '',
    accountType: 'Expense',
    notes: 'Sprinkler and fire protection system repairs',
  },
  {
    sourceLabel: '6203 R&M Lighting/Electrical',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Lighting and electrical repairs',
  },
  {
    sourceLabel: '6204 R & M Plumbing',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Plumbing repairs',
  },
  {
    sourceLabel: '6206 R & M Exterior Building Repair',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Exterior building repairs',
  },
  {
    sourceLabel: 'Repairs & Maintenance',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes:
      'CubeSmart R&M subtotal — its group also carries cameras and fire protection, which map elsewhere; do not aggregate in model',
  },
  {
    sourceLabel: '6122 Training',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Staff training',
  },
  {
    sourceLabel: '6152 Uniforms',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Staff uniforms',
  },
  {
    sourceLabel: '6159 Sales Center',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'National call center allocation',
  },
  {
    sourceLabel: '6163 Help Desk',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'IT help desk allocation',
  },
  {
    sourceLabel: '6162 Supplies',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Store operating supplies',
  },
  {
    sourceLabel: '6164 Sale Items',
    coa: 'Retail Products',
    coa2: '',
    accountType: 'Expense',
    notes: 'Cost of retail merchandise sold',
  },
  {
    sourceLabel: '6168 Dues & Subscriptions',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Association dues and subscriptions',
  },
  {
    sourceLabel: '6170 Landscaping',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Grounds and landscaping maintenance',
  },
  {
    sourceLabel: '6174 Signs',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Property signage',
  },
  {
    sourceLabel: '6176 Auto Expense',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Vehicle and mileage costs',
  },
  {
    sourceLabel: '6182 Fees / Licenses',
    coa: 'Licenses & Permits',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business licenses, permits, and operational fees',
  },
  {
    sourceLabel: '6190 Postage',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Postage and delivery',
  },
  {
    sourceLabel: '6212 Office Supplies',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Office supplies and general administrative costs',
  },
  {
    sourceLabel: '6218 Printing Expense',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Printing and reproduction',
  },
  {
    sourceLabel: '6220 Equipment',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Small equipment purchases',
  },
  {
    sourceLabel: '6223 Money Order Fees',
    coa: 'Bank Charges',
    coa2: '',
    accountType: 'Expense',
    notes: 'Money order processing fees',
  },
  {
    sourceLabel: '6224 Computer Expense',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Computer hardware and support',
  },
  {
    sourceLabel: '6225 Cms License Fee',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'CubeSmart property management system licence',
  },
  {
    sourceLabel: '6226 Bank Charges',
    coa: 'Bank Charges',
    coa2: '',
    accountType: 'Expense',
    notes: 'Bank service charges',
  },
  {
    sourceLabel: '6228 Bank Adjustments',
    coa: 'Bank Charges',
    coa2: '',
    accountType: 'Expense',
    notes: 'Bank reconciliation adjustments',
  },
  {
    sourceLabel: '6232 Visa/Mastercard Fees',
    coa: 'Current Payment Processing Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'Card processing costs',
  },
  {
    sourceLabel: '6233 American Express Fees',
    coa: 'Current Payment Processing Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'Card processing costs',
  },
  {
    sourceLabel: '6235 Ach Fees',
    coa: 'Current Payment Processing Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'ACH payment processing costs',
  },
  {
    sourceLabel: '6249 Meals & Entertainment',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Meals and entertainment',
  },
  {
    sourceLabel: '6256 Legal/Auction',
    coa: 'Prof Fees - Legal/Acctg',
    coa2: '',
    accountType: 'Expense',
    notes: 'CubeSmart reports legal fees and lien auction costs on one line',
  },
  {
    sourceLabel: 'Other Controllable Expenses',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes:
      'CubeSmart other controllable subtotal — spans office, software, retail, licence, and bank costs, so it has no single COA; do not aggregate in model',
  },
  {
    sourceLabel: '6365 Internet/Website Costs',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Digital and internet advertising spend',
  },
  {
    sourceLabel: '6375 Store Marketing',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Local store marketing',
  },
  {
    sourceLabel: 'Marketing Expense',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart marketing subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Total Controllable Expense',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart controllable expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: '7030 Sales Tax Collection Allowance',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Sales tax collection allowance retained by the store',
  },
  {
    sourceLabel: 'Other Income',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart other income subtotal — do not aggregate in model',
  },
  {
    sourceLabel: '6172 Snow Removal & Salting',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Snow removal and salting',
  },
  {
    sourceLabel: '6801 Third Party Management Fees',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'Expense',
    notes: 'Third-party management fee paid to CubeSmart',
  },
  {
    sourceLabel: 'Other Non Controllable Expenses',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart other non-controllable subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Non Controllable Expenses',
    coa: '',
    coa2: '',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart non-controllable expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Total Operating Expenses',
    coa: 'Total Operating Expense',
    coa2: 'Total Operating Expense',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart total operating expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Net Operating Income (Loss)',
    coa: 'Net Operating Income',
    coa2: 'Net Operating Income',
    accountType: 'CS_Rollup',
    notes: 'CubeSmart calculated NOI — do not aggregate in model',
  },
];

/** alias_mappings_ps.csv currently holds only its header row. */
const ALIAS_PS: AliasMappingRow[] = [];

/**
 * CubeSmart writes the same account with and without spaces around the
 * ampersand, and abbreviates a few names between store charts. A leading GL code
 * needs no alias - normalizeLabel already strips it.
 */
const ALIAS_CS: AliasMappingRow[] = [
  { alias: 'R&M Doors', canonicalLabel: '6194 R & M Doors', notes: '' },
  { alias: 'R&M Cameras', canonicalLabel: '6198 R & M Cameras', notes: '' },
  { alias: 'R&M Hvac', canonicalLabel: '6199 R & M Hvac', notes: '' },
  { alias: 'R&M Plumbing', canonicalLabel: '6204 R & M Plumbing', notes: '' },
  {
    alias: 'R&M Exterior Building Repair',
    canonicalLabel: '6206 R & M Exterior Building Repair',
    notes: '',
  },
  { alias: 'R & M Fire Protection', canonicalLabel: '6201 R&M Fire Protection', notes: '' },
  { alias: 'R & M Lighting/Electrical', canonicalLabel: '6203 R&M Lighting/Electrical', notes: '' },
  { alias: 'Fees/Licenses', canonicalLabel: '6182 Fees / Licenses', notes: '' },
  { alias: 'Water & Sewer', canonicalLabel: '6186 Water/Sewer', notes: '' },
  { alias: 'Trash Removal', canonicalLabel: '6150 Rubbish Removal', notes: '' },
  { alias: 'Snow Removal', canonicalLabel: '6172 Snow Removal & Salting', notes: '' },
  {
    alias: 'Management Fees',
    canonicalLabel: '6801 Third Party Management Fees',
    notes: '',
  },
  { alias: 'Discounts Charged', canonicalLabel: '4700 Discounts Charged - Rent', notes: '' },
  { alias: 'Convenience Fee', canonicalLabel: '4286 Convenience Fee Payments', notes: '' },
  { alias: 'Tenant Insurance', canonicalLabel: '4920 Tenant Pd Insurance', notes: '' },
  { alias: 'Workers Compensation', canonicalLabel: '6283 Workers Comp Premium', notes: '' },
  { alias: 'Internet/Website Cost', canonicalLabel: '6365 Internet/Website Costs', notes: '' },
];

/**
 * StorQuest accounts, in Rolling 13 order.
 *
 * Source labels are stored without the GL prefix StorQuest writes in front of
 * every account ('108-9132-7600-4000-05 Rental Income'), because the second
 * segment of that prefix is the property number and would pin each row to one
 * store. normalizeLabel strips it, so these resolve on the normalized pass.
 *
 * StorQuest runs on the same account numbering as Extra Space - 4000 rental,
 * 5100 management fee, 5670 fire prevention - so where a code matches, the COA
 * here matches APPROVED_EXR for that code.
 */
const APPROVED_SQ: ApprovedMappingEntry[] = [
  {
    sourceLabel: 'Rental Income',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Core storage unit rental revenue',
  },
  {
    sourceLabel: 'Parking Rental Income',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Parking rental — combine with storage rental income per COA Translation',
  },
  {
    sourceLabel: 'Customer Rent Refunds',
    coa: 'Rental Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-revenue — tenant refunds reduce gross rental income',
  },
  {
    sourceLabel: 'Discounts Write-Off',
    coa: 'Discounts',
    coa2: '',
    accountType: 'Income',
    notes: 'Move-in specials and promotional concessions',
  },
  {
    sourceLabel: 'Bad Debt Expense',
    coa: 'Bad Debt',
    coa2: '',
    accountType: 'Income',
    notes: 'Uncollectible rent written off',
  },
  {
    sourceLabel: 'Total Rental Income',
    coa: 'Net Rental Income',
    coa2: 'Net Rental Income',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest net rental income subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Late Fees',
    coa: 'Late Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Late fees charged to tenants',
  },
  {
    sourceLabel: 'NSF & Other Fees',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Returned payment and miscellaneous tenant fees',
  },
  {
    sourceLabel: 'Administration Fees',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Move-in administrative fee',
  },
  {
    sourceLabel: 'Fees Waived-Admin',
    coa: 'Admin Fee Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Contra-account — offsets gross admin fees',
  },
  {
    sourceLabel: 'Total Fee Income',
    coa: '',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes:
      'StorQuest fee subtotal — spans admin, late, and other fee income, so it has no single COA; do not aggregate in model',
  },
  {
    sourceLabel: 'Merchandise Sales',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Merchandise and retail supply sales',
  },
  {
    sourceLabel: 'Total Merchandise Sales',
    coa: 'Retail Sales Income',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest merchandise subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Insurance Referral Income',
    coa: 'Current Tenant Protection Split',
    coa2: '',
    accountType: 'Income',
    notes: 'Tenant protection plan revenue split',
  },
  {
    sourceLabel: 'Total Insurance Referral Income',
    coa: 'Current Tenant Protection Split',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest tenant insurance subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Miscellaneous Income',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'Income',
    notes: 'Miscellaneous other operating income',
  },
  {
    sourceLabel: 'Total Income - Other',
    coa: 'Other Tenant Income',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest other income subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Total Income',
    coa: 'Total Operating Income',
    coa2: 'Total Operating Income',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest total revenue subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Wages',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Site staff wages',
  },
  {
    sourceLabel: 'Overtime',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Manager and staff overtime pay',
  },
  {
    sourceLabel: 'Vacation & Personal Leave',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'PTO and vacation pay accruals',
  },
  {
    sourceLabel: 'Performance Bonus',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Annual and periodic performance bonuses',
  },
  {
    sourceLabel: '401K Match',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer 401K contribution',
  },
  {
    sourceLabel: 'Mileage',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Staff mileage reimbursement',
  },
  {
    sourceLabel: 'Personnel Expenses',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Miscellaneous personnel costs',
  },
  {
    sourceLabel: 'Group Health & Life Insurance',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employee health and life insurance benefits',
  },
  {
    sourceLabel: 'Payroll Service',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Payroll processing service',
  },
  {
    sourceLabel: 'Payroll Taxes',
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Employer FICA/FUTA/SUTA payroll taxes',
  },
  {
    sourceLabel: "Workman's Comp",
    coa: 'Payroll',
    coa2: '',
    accountType: 'Expense',
    notes: 'Workers compensation insurance premiums',
  },
  {
    sourceLabel: 'Total Payroll',
    coa: 'Payroll',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest payroll subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Management Fees',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'Expense',
    notes: 'Third-party management fee paid to StorQuest',
  },
  {
    sourceLabel: 'Total Management Fee',
    coa: 'Current Mgmt. Fee',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest management fee subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Online Advertising',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Digital and internet advertising spend',
  },
  {
    sourceLabel: 'Cause / Charity',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Community sponsorship and charitable giving',
  },
  {
    sourceLabel: 'Content Advertising',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Content and creative marketing spend',
  },
  {
    sourceLabel: 'Other Advertising',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'Traditional and non-digital advertising spend',
  },
  {
    sourceLabel: 'Total Advertising',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest advertising subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Gas & Electric',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Gas and electric utility',
  },
  {
    sourceLabel: 'Water & Sewer',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Water and sewer utility',
  },
  {
    sourceLabel: 'Total Utilities',
    coa: 'Utilities',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest utilities subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Office Supplies',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Office supplies and general administrative supplies',
  },
  {
    sourceLabel: 'Postage & Delivery',
    coa: 'Office Supplies',
    coa2: '',
    accountType: 'Expense',
    notes: 'Postage and express shipping costs',
  },
  {
    sourceLabel: 'Dues & Subscriptions',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Association dues and subscriptions',
  },
  {
    sourceLabel: 'Bank Charges',
    coa: 'Bank Charges',
    coa2: '',
    accountType: 'Expense',
    notes: 'Bank service charges and fees',
  },
  {
    sourceLabel: 'Credit Card Fees',
    coa: 'Current Payment Processing Fees',
    coa2: '',
    accountType: 'Expense',
    notes: 'Credit and debit card processing costs',
  },
  {
    sourceLabel: 'Accounting Fees',
    coa: 'Prof Fees - Legal/Acctg',
    coa2: '',
    accountType: 'Expense',
    notes: 'Accounting and bookkeeping fees',
  },
  {
    sourceLabel: 'License',
    coa: 'Licenses & Permits',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business licenses and operational taxes',
  },
  {
    sourceLabel: 'Education & Training',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Staff training and education',
  },
  {
    sourceLabel: 'Outside Services',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Contracted outside services',
  },
  {
    sourceLabel: 'Travel',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Business travel',
  },
  {
    sourceLabel: 'Meals',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Meals and entertainment',
  },
  {
    sourceLabel: 'Uniforms',
    coa: 'Other Expense',
    coa2: '',
    accountType: 'Expense',
    notes: 'Staff uniforms',
  },
  {
    sourceLabel: 'Lien Sale',
    coa: 'Auction',
    coa2: '',
    accountType: 'Expense',
    notes: 'Lien sale and auction costs',
  },
  {
    sourceLabel: 'Lock & Box Expense',
    coa: 'Retail Products',
    coa2: '',
    accountType: 'Expense',
    notes: 'Cost of retail merchandise sold',
  },
  {
    sourceLabel: 'Total Office Supplies',
    coa: '',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes:
      'StorQuest office subtotal — its group also carries bank, card, licence, lien sale, and lock and box costs, which map elsewhere; do not aggregate in model',
  },
  {
    sourceLabel: 'Telephone/Internet',
    coa: 'Telephone & Internet',
    coa2: '',
    accountType: 'Expense',
    notes: 'Phone and internet service for the property',
  },
  {
    sourceLabel: 'Call Center',
    coa: 'Advertising & Marketing',
    coa2: '',
    accountType: 'Expense',
    notes: 'National call center costs',
  },
  {
    sourceLabel: 'Software',
    coa: 'Software',
    coa2: '',
    accountType: 'Expense',
    notes: 'Property management and office software',
  },
  {
    sourceLabel: 'Total Phone and Computer',
    coa: '',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes:
      'StorQuest phone and computer subtotal — spans telephone, call center, and software, which map to three COA lines; do not aggregate in model',
  },
  {
    sourceLabel: 'Building Repairs & Maintenance',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'General facility repairs and maintenance',
  },
  {
    sourceLabel: 'Maintenance Supplies',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Maintenance parts and supplies',
  },
  {
    sourceLabel: 'Trash Removal',
    coa: 'Utilities',
    coa2: '',
    accountType: 'Expense',
    notes: 'Trash collection service',
  },
  {
    sourceLabel: 'Landscaping',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Grounds and landscaping maintenance',
  },
  {
    sourceLabel: 'Pest Control',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Pest control service',
  },
  {
    sourceLabel: 'Security',
    coa: 'Security',
    coa2: '',
    accountType: 'Expense',
    notes: 'Security system and monitoring',
  },
  {
    sourceLabel: 'Gate Repairs',
    coa: 'Repairs & Maintenance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Gate and fence repairs',
  },
  {
    sourceLabel: 'Fire Prevention',
    coa: 'Fire Prevention',
    coa2: '',
    accountType: 'Expense',
    notes: 'Sprinkler and fire protection service',
  },
  {
    sourceLabel: 'Total Repairs and Maintenance',
    coa: '',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes:
      'StorQuest R&M subtotal — its group also carries trash removal and security, which map elsewhere; do not aggregate in model',
  },
  {
    sourceLabel: 'Property & Liability Insurance',
    coa: 'Insurance',
    coa2: '',
    accountType: 'Expense',
    notes: 'Property and casualty insurance premiums',
  },
  {
    sourceLabel: 'Total Insurance Expense',
    coa: 'Insurance',
    coa2: '',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest insurance subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Total Operating Expenses',
    coa: 'Total Operating Expense',
    coa2: 'Total Operating Expense',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest total operating expense subtotal — do not aggregate in model',
  },
  {
    sourceLabel: 'Net Operating Income',
    coa: 'Net Operating Income',
    coa2: 'Net Operating Income',
    accountType: 'SQ_Rollup',
    notes: 'StorQuest calculated NOI — do not aggregate in model',
  },
];

/**
 * The Rolling 13 summary sheet names its section subtotals without the "Total"
 * prefix the detailed sheet uses, so those spellings map to the same rows.
 */
const ALIAS_SQ: AliasMappingRow[] = [
  { alias: 'Fee Income', canonicalLabel: 'Total Fee Income', notes: '' },
  { alias: 'Payroll', canonicalLabel: 'Total Payroll', notes: '' },
  { alias: 'Management Fee', canonicalLabel: 'Total Management Fee', notes: '' },
  { alias: 'Advertising', canonicalLabel: 'Total Advertising', notes: '' },
  { alias: 'Utilities', canonicalLabel: 'Total Utilities', notes: '' },
  { alias: 'Phone and Computer', canonicalLabel: 'Total Phone and Computer', notes: '' },
  {
    alias: 'Repairs and Maintenance',
    canonicalLabel: 'Total Repairs and Maintenance',
    notes: '',
  },
  { alias: 'Insurance Expense', canonicalLabel: 'Total Insurance Expense', notes: '' },
  { alias: 'Income - Other', canonicalLabel: 'Total Income - Other', notes: '' },
  { alias: 'Gas and Electric', canonicalLabel: 'Gas & Electric', notes: '' },
  { alias: 'Water and Sewer', canonicalLabel: 'Water & Sewer', notes: '' },
  { alias: 'Workmans Comp', canonicalLabel: "Workman's Comp", notes: '' },
  { alias: 'Telephone / Internet', canonicalLabel: 'Telephone/Internet', notes: '' },
];

export const APPROVED_MAPPINGS: Record<CoaTableKey, ApprovedMappingEntry[]> = {
  exr: APPROVED_EXR,
  ps: APPROVED_PS,
  cs: APPROVED_CS,
  sq: APPROVED_SQ,
};

export const ALIAS_MAPPINGS: Record<CoaTableKey, AliasMappingRow[]> = {
  exr: ALIAS_EXR,
  ps: ALIAS_PS,
  cs: ALIAS_CS,
  sq: ALIAS_SQ,
};

/**
 * Maps each Managed By option to its mapping table.
 * null means skip COA mapping for that manager (manual review required).
 */
export const COA_TABLE_BY_MANAGER: Record<ManagedBy, CoaTableKey | null> = {
  Extra: 'exr',
  'Public Storage': 'ps',
  CubeSmart: 'cs',
  StorQuest: 'sq',
  Other: null,
};
